#!/bin/sh

echo 'Installing Modules..'
npm install
echo 'Modules installed!"'
echo 'Configuring Security Settings..'
mkdir -p certificates
openssl genrsa -out certificates/jwt.key 4096
echo 'Compressing JS..'
terser common.js --output common.js --compress --mangle 
terser public/quiz.js --output public/quiz.js --compress --mangle 
echo 'Converting all .png, .jpg, and .jpeg files to .webp...'
for f in $(find . -name '*.png' -or -name '*.jpg' -or -name '*.jpeg'); do 
    if [ ! -f "${f%.*}.webp" ]; then
        cwebp -q 60 $f -o ${f%.*}.webp
    fi
done
echo 'Shutting down the server..'
pm2 delete 'all'
echo 'Starting server..'
set NODE_ENV=production && pm2 start index.js
pm2 start ./daemons/subscription.daemons.js